// Card selection from the bundled card database (data/cards.json).
//
// The live api.pokemontcg.io is far too slow for gameplay (multi-second
// responses are common), so all card data ships with the app — generated by
// scripts/generate-card-data.mjs. Only the card *images* load from the
// network, served by the fast images.pokemontcg.io CDN.

import cardData from '@/data/cards.json';

interface StoredCard {
  id: string;
  name: string;
  number: string;
  types?: string[];
  evolvesFrom?: string;
  flavorText?: string;
  ability?: { name: string; text: string; type: string };
  artist?: string;
  images?: { small: string; large: string };
}

interface StoredSet {
  id: string;
  name: string;
  series: string;
  cards: StoredCard[];
}

export interface PokemonCard {
  id: string;
  name: string;
  types?: string[];
  evolvesFrom?: string;
  flavorText?: string;
  abilities?: Array<{ name: string; text: string; type: string }>;
  images: {
    small: string;
    large: string;
  };
  artist?: string;
  set: {
    id: string;
    name: string;
    series: string;
  };
}

export interface Round {
  card: PokemonCard;
  distractors: string[];
}

const SETS = (cardData as { sets: StoredSet[] }).sets;
const TOTAL_CARDS = SETS.reduce((n, s) => n + s.cards.length, 0);

/** Unbiased Fisher-Yates shuffle (returns a new array). */
export function shuffle<T>(arr: T[]): T[] {
  const out = [...arr];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function toPokemonCard(card: StoredCard, set: StoredSet): PokemonCard {
  return {
    id: card.id,
    name: card.name,
    types: card.types,
    evolvesFrom: card.evolvesFrom,
    flavorText: card.flavorText,
    abilities: card.ability ? [card.ability] : undefined,
    artist: card.artist,
    images: card.images ?? {
      small: `https://images.pokemontcg.io/${set.id}/${card.number}.png`,
      large: `https://images.pokemontcg.io/${set.id}/${card.number}_hires.png`,
    },
    set: { id: set.id, name: set.name, series: set.series },
  };
}

/** Pick a card uniformly across every card in the database. */
export function getRandomRound(distractorCount = 3): Round {
  let index = Math.floor(Math.random() * TOTAL_CARDS);
  let set = SETS[0];
  for (const s of SETS) {
    if (index < s.cards.length) {
      set = s;
      break;
    }
    index -= s.cards.length;
  }
  const card = set.cards[index];

  // Distractors from the same set feel fair and era-appropriate; different
  // evolutions of the same Pokémon share a name, so dedupe by name
  const sameSetNames = [...new Set(set.cards.map((c) => c.name))].filter((n) => n !== card.name);
  const distractors = shuffle(sameSetNames).slice(0, distractorCount);

  // Tiny sets might not have enough names — pad from other sets
  while (distractors.length < distractorCount) {
    const other = SETS[Math.floor(Math.random() * SETS.length)];
    const pick = other.cards[Math.floor(Math.random() * other.cards.length)].name;
    if (pick !== card.name && !distractors.includes(pick)) distractors.push(pick);
  }

  return { card: toPokemonCard(card, set), distractors };
}
